spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: junho
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    redis:
      port: 6379
      host: 127.0.0.1
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              spi: trace