spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: junho
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    prefix: classpath:/templates/  # Thymeleaf 템플릿이 위치한 디렉토리
    suffix: .html  # 템플릿 파일 확장자
    cache: false  # 개발 중이라면 캐싱을 비활성화
    mode: HTML5  # HTML5 모드 사용
  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1

logging:
  level:
    org:
      hibernate:
        sql: debug
        type:
          descriptor:
            sql:
              spi: trace
